name: Mobile Tests CI

on: [push, pull_request]

jobs:
  android-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run Android Espresso Tests
        working-directory: android-tests
        run: ./gradlew connectedAndroidTest

  ios-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Run iOS XCUITests
        working-directory: ios-tests
        run: xcodebuild test -scheme MyAppUITests -destination 'platform=iOS Simulator,name=iPhone 14'